### ISSUE TITLE
Yohe build sould create the dir `source/_extra`

### ISSUE THREAD

**Issue by kigiri** [laoqiren/yohe#2]
Yohe build sould create the dir `source/_extra`

<img width="789" alt="screen shot 2017-10-06 at 16 00 34" src="https://user-images.githubusercontent.com/231748/31287082-aa724b54-aaaf-11e7-8597-2be68de51b04.png">

After manualy creating the folder it all worked fine 👍

**Comment by laoqiren** [comment]
Thanks for your issue, this happens because the `npm` and `git` will not upload empty folders by default. I will fix this.
